Function Login, Register, Get Profile, Edit
cifacademy/Student_HG_Laravel pull request #4
Opened 2022-12-05 15:29 UTC by Hedo21

# Description

I have created login, register, get profile, edit functions. The get profile function is still waiting for confirmation on what can be displayed. The edit function is also still waiting for confirmation of what data can be edited.

JSON Contract :
1.  Register
request parameter:
{ 
   "name" : "string",
   "username" : "string" 
   "email": "string"
   "password": "string" 
}

2.  Login
request parameter:
{ 
   "name" : "string",
   "password" : "string" 
}

Message
1. Register Success
{  
    "success": true,
    "access_token": "48|TPQ3PJATgblaym6Axo0PdHajd9BjMEQRVxplsxtj",
    "message": "Berhasil Registrasi!"
}

2. Register Failed
{
    "name": [
        "Masukkan nama"
    ],
    "username": [
        "Masukkan username"
    ],
    "email": [
        "Masukkan email"
    ],
    "password": [
        "Masukkan password"
    ]
}

3. Login Success
{
    "message": "Login Berhasil",
    "access_token": "49|rz1dcJqTOGU0rLgLvy8bTYYdOcdZ29rw0qlGugjG",
    "token_type": "Bearer"
}

4. Login failed
{
    "errors": [
        "The email field is required.",
        "The password field is required."
    ]
}

## Task reference

Please include the task reference link and details (name, requirement, etc) here.

> **Example:** Create a login page for the student. [Task Reference](https://put_task_reference_link_here)

## Type of change

Please make any relevant options for the progress of your changes.

> Example for creating login page task :
> - [x] Make login form
> - [ ] Make form validation for email
> - [ ] Make form validation for empty form

# How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] User Interface Local
- [ ] Postman Response
- [ ] User Test

## Testing screenshot

Please provide us with your test results. This may be a positive or negative test for an API response. Also, provide us with the interface before and after your changes are applied if any. Provide a relevant title.

### Before my change

*Place your screenshot here*

### After my change

*Place your screenshot here*

# Checklist:

- [ ] My changes do not affect any errors in existing features
- [ ] Perform `git pull --rebase origin main` before ready to merge
- [ ] No conflict in my changes
- [ ] Any conflicts are resolved
- [ ] I've follows [the code style guidelines](https://)
- [ ] I've follows [the code documentation guidelines](https://)
- [ ] I've added and run a test scenario that proves my changes are works
- [ ] I've provided  all relevant screenshots
- [ ] My changes generate no new warnings and no error
- [ ] Approve by at least  2 or more tech member
- [ ]  Approve by the project owner
- [ ] Using all relevant labels

2022-12-05 18:01 UTC, chamisfum reviewed
@darmainchiro iki haruse nang folder `heroguru-api-app` kan?

2022-12-05 18:14 UTC, chamisfum reviewed
mas @Hedo21 Aku minta tolong nanti response nya kaya gini ya

1. Success
```json
{ 
      "status":"success"
      "access_token": "48|TPQ3PJATgblaym6Axo0PdHajd9BjMEQRVxplsxtj",
      "message": "registration successful"
}
```

2. Register Failed
```json
{
    "status":"failed",
    "message":"invalid email address"
}
```

Tolong tambahkan list message yang mungkin terjadi yaa:

```json
["invalid email address", *****]
```

3. Login Success
```JSON
{
    "status":"success"
    "message": "login success",
    "access_token": "49|rz1dcJqTOGU0rLgLvy8bTYYdOcdZ29rw0qlGugjG",
    "token_type": "Bearer"
    
}
```

4. Login failed
```JSON
{
    "status":"failed"
    "errors": "invalid email address"
}
```
Tolong tambahkan list message yang mungkin terjadi yaa:

```json
["email required", "password required", "invalid email", "invalid password", *****]
```

2022-12-06 03:48 UTC, Hedo21 commented
iya mas kubenerin dulu

2022-12-07 00:55 UTC, chamisfum requested changes
ada komen dikit ya @Hedo21 

> catatan : 
> 1. untuk json contract gunakan huruf kecil semua baik key atau valuenya.
> 2. untuk key gunakan `snake_case`
> 3. pastikan untuk menambahkan `status` dan `message` untuk setiap response yang ada.
> 4. untuk value boleh menggunakan bahasa inggris atau bahasa indonesia
> 5. untuk key gunakan bahasa inggris 

Terimakasih

2022-12-07 00:55 UTC, chamisfum commented on Student_HG_Laravel/app/Http/Controllers/AuthController.php
> +                'password.required' => 'Enter Your Password',
Saran untuk json value pake lowercase saja yaa
```suggestion
                'name.required'     => 'name is empty',
                'username.required' => 'username is empty',
                'email.required'    => 'email is empty',
                'password.required' => 'password is empty',
```

2022-12-07 00:55 UTC, chamisfum commented on Student_HG_Laravel/app/Http/Controllers/AuthController.php
> +            return response()->json($validator->errors());
Ini kurang statusnya mas. Nanti jangan lupa di update di deskripsi juga ya hasil testingnya 💪 

```suggestion
return response()->json(
     [
          'status' => 'failed',
          'message' => $validator->errors()->all()
     ]
);
```

2022-12-07 00:55 UTC, chamisfum commented on Student_HG_Laravel/app/Http/Controllers/AuthController.php
> +                    'message'      => 'Registration Success',
```suggestion
                    'status'       => 'success',
                    'access_token' => $token,
                    'message'      => 'registration success',
```

2022-12-07 00:55 UTC, chamisfum commented on Student_HG_Laravel/app/Http/Controllers/AuthController.php
> +                    'message' => 'Registration Failed',
```suggestion
                    'status'  => 'failed',
                    'message' => 'registration railed',
```

2022-12-07 00:55 UTC, chamisfum commented on Student_HG_Laravel/app/Http/Controllers/AuthController.php
> +                'password.required' => 'Enter Your Password',
```suggestion
                'email.required'    => 'email is empty',
                'password.required' => 'password email is empty',
```

2022-12-07 00:55 UTC, chamisfum commented on Student_HG_Laravel/app/Http/Controllers/AuthController.php
> +                    'message' => 'Password Incorrect',
```suggestion
                    'stutus'  => 'failed',
                    'message' => 'incorrect password',
```

2022-12-07 00:55 UTC, chamisfum commented on Student_HG_Laravel/app/Http/Controllers/AuthController.php
> +                    'token_type'   => 'Bearer',
```suggestion
                    'status'       => 'success',
                    'message'      => 'login success',
                    'access_token' => $token,
                    'token_type'   => 'bearer',
```

2022-12-07 00:55 UTC, chamisfum commented on Student_HG_Laravel/app/Http/Controllers/AuthController.php
> +                'message' => 'Wrong Email or Unregistered Email'
```suggestion
                'status'  => 'failed',
                'message' => 'wrong email or unregistered email'
```

2022-12-07 00:55 UTC, chamisfum commented on Student_HG_Laravel/app/Http/Controllers/AuthController.php
> +                'message' => 'Data Berhasil Ditampilkan'
```suggestion
                'status' => 'success',
                auth()->user(),
                'message' => 'data berhasil ditampilkan'
```

2022-12-07 00:55 UTC, chamisfum commented on Student_HG_Laravel/app/Http/Controllers/AuthController.php
> +            return response(['errors' => $validator->errors()->all()], 422);
```suggestion
            return response([
                'status' => `error`
                'message' => $validator->errors()->all()
            ], 422);
```

2022-12-07 00:55 UTC, chamisfum commented on Student_HG_Laravel/app/Http/Controllers/AuthController.php
> +                'password.required' => 'Masukkan Password baru'
```suggestion
                'name.required'     => 'name is empty',
                'password.required' => 'password is empty'
```

2022-12-07 00:55 UTC, chamisfum commented on Student_HG_Laravel/app/Http/Controllers/AuthController.php
> +                'data'    => $validator->errors()
```suggestion
                'status' => 'failed',
                'message' => 'update failed',
                'data'    => $validator->errors()
```

2022-12-07 00:55 UTC, chamisfum commented on Student_HG_Laravel/app/Http/Controllers/AuthController.php
> +                    'message' => 'sukses diperbarui',
```suggestion
                    'status' => 'success',
                    'id'      => $valid->id,
                    'message' => 'update succeed',
```

2022-12-07 00:55 UTC, chamisfum commented on Student_HG_Laravel/app/Http/Controllers/AuthController.php
> +                    'message' => 'gagal',
```suggestion
                    'status' => 'failed',
                    'message' => 'update failed',
```

2022-12-07 08:19 UTC, Hedo21 commented
oke mas @chamisfum cuman ku lanjutin jumat ya mas, ada dedlen tugas besar kuliah kamis mas, mau nyicil itu dulu

2022-12-08 08:25 UTC, chamisfum commented on Student_HG_Laravel/app/Http/Controllers/AuthController.php
> +                    'message' => 'gagal',
Oke @Hedo21  lek bales disini aja mas ga perlu comment di tempat lain yaa

2022-12-10 15:30 UTC, Hedo21 commented on Student_HG_Laravel/app/Http/Controllers/AuthController.php
> +                    'message' => 'gagal',
@chamisfum udah ku benerin mas

2022-12-11 05:43 UTC, chamisfum approved these changes
LGTM

2022-12-11 07:19 UTC, chamisfum reviewed
Need adding new variable `role`

Register request from FE
```json
{ 
   "name" : "string",
   "username" : "string" 
   "email": "string"
   "password": "string" 
   "role" : "string" // get from onboarding (dapat dari cache atau variable yang dikirim dari sesi on boarding)
}
```

Login request from FE
```json
{ 
   "email": "string"
   "password": "string" 
   "role" : "string" // get from onboarding (dapat dari cache atau variable yang dikirim dari sesi on boarding)
}
```

@Hedo21 

![image](https://user-images.githubusercontent.com/34487579/206891172-296899d8-c304-4a52-b478-8db11e9649f3.png)

2022-12-15 07:03 UTC, darmainchiro approved these changes

2022-12-15 07:04 UTC, darmainchiro commented
iyo neng heroguru-api-app

2022-12-15 12:46 UTC, merged